---
- name: ReadJsonfile
  hosts: localhost
  vars:
    input: "{{ lookup('file','file.json') | from_json }}"
  tasks:

  - name: loop the loop
    debug:
      msg: "jdbc_data_source name is {{ item[1].name }} has username {{ item[2].jdbc_driver_params[2].properties.property[0].name }} and jndi name {{ item[3].jdbc_data_source_params.jndi_name }}"
    loop: "{{ input | json_query('[*].jdbc_data_source[*]') }}"
